import os
import asyncio
from google import genai
from google.genai import types
from .logging_service import logger

async def generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by Imagen 3 (Async).
    """
    logger.info(f"Generating image with prompt: {prompt}...")
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        logger.error("GOOGLE_API_KEY not found in environment variables.")
        raise RuntimeError("GOOGLE_API_KEY is not set.")

    try:
        client = genai.Client(api_key=api_key)

        # Using the official Imagen 3 model for high-quality technical diagrams
        # This model is dedicated to image generation
        response = await asyncio.to_thread(
            client.models.generate_image,
            model='imagen-3.0-generate-001',
            prompt=prompt,
            config=types.GenerateImageConfig(
                number_of_images=1,
                include_rai_reason=True,
                output_mime_type='image/png'
            )
        )
        
        if not response.generated_images:
            raise RuntimeError("Imagen 3 did not return any images. Check your safety settings or quota.")

        logger.info("Successfully received high-quality image from Imagen 3 API.")
        return response.generated_images[0].image_bytes

    except Exception as e:
        logger.error(f"Imagen API Error: {e}")
        # Fallback error message for the user to see in logs
        raise RuntimeError(f"Imagen Generation Failed: {str(e)}")
