import os
import asyncio
from google import genai
from google.genai import types
from .logging_service import logger

async def generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by Gemini (Async).
    """
    logger.info(f"Generating image with prompt: {prompt}...")
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        logger.error("GOOGLE_API_KEY not found in environment variables.")
        raise RuntimeError("GOOGLE_API_KEY is not set.")

    try:
        client = genai.Client(api_key=api_key)

        # Standard safety settings
        safety_settings = [
            types.SafetySetting(category="HARM_CATEGORY_HATE_SPEECH", threshold="BLOCK_NONE"),
            types.SafetySetting(category="HARM_CATEGORY_HARASSMENT", threshold="BLOCK_NONE"),
            types.SafetySetting(category="HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold="BLOCK_NONE"),
            types.SafetySetting(category="HARM_CATEGORY_DANGEROUS_CONTENT", threshold="BLOCK_NONE"),
        ]

        # Use the correct stable model for Gemini 2.0 image generation
        # 'gemini-2.0-flash' is the standard model identifier
        resp = await asyncio.to_thread(
            client.models.generate_content,
            model="gemini-2.0-flash", 
            contents=prompt,
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
                safety_settings=safety_settings,
            ),
        )
        logger.debug("Successfully received response from Gemini Image API.")
    except Exception as e:
        logger.error(f"Gemini Image API request failed: {e}")
        raise

    parts = getattr(resp, "parts", None)
    if not parts and getattr(resp, "candidates", None):
        try:
            parts = resp.candidates[0].content.parts
        except Exception as e:
            logger.error(f"Failed to parse candidates from response: {e}")
            parts = None

    if not parts:
        logger.warning("No image content returned in the response (possibly safety/quota).")
        raise RuntimeError("No image content returned from Gemini.")

    for part in parts:
        inline = getattr(part, "inline_data", None)
        if inline and getattr(inline, "data", None):
            logger.info("Successfully extracted image bytes.")
            return inline.data

    logger.warning("No inline image bytes found in response parts.")
    raise RuntimeError("No image bytes found in Gemini response.")
