import os
import asyncio
from google import genai
from google.genai import types
from .logging_service import logger


async def generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by Gemini (Async).
    Model: gemini-2.5-flash-image
    """
    logger.info(f"Generating Gemini image with prompt: {prompt}...")

    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        logger.error("GOOGLE_API_KEY not found in environment variables.")
        raise RuntimeError("GOOGLE_API_KEY is not set.")

    try:
        client = genai.Client(api_key=api_key)

        # Run blocking SDK call in thread (async-safe)
        resp = await asyncio.to_thread(
            client.models.generate_content,
            model="gemini-2.5-flash-image",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
                safety_settings=[
                    types.SafetySetting(
                        category="HARM_CATEGORY_DANGEROUS_CONTENT",
                        threshold="BLOCK_ONLY_HIGH",
                    )
                ],
            ),
        )

        # ---- Robust extraction logic (SDK-safe) ----

        parts = getattr(resp, "parts", None)

        if not parts and getattr(resp, "candidates", None):
            try:
                parts = resp.candidates[0].content.parts
            except Exception:
                parts = None

        if not parts:
            raise RuntimeError("No image content returned (safety block, quota issue, or SDK structure change).")

        for part in parts:
            inline = getattr(part, "inline_data", None)
            if inline and getattr(inline, "data", None):
                logger.info("Successfully extracted image bytes from Gemini response.")
                return inline.data

        raise RuntimeError("No inline image bytes found in Gemini response.")

    except Exception as e:
        logger.error(f"Gemini Image API request failed: {e}")
        raise RuntimeError(f"Gemini Generation Failed: {str(e)}")